version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=croquis
      - TZ=UTC
    ports:
      - "3306:3306"